server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Cache control for Service Worker and manifest files
    location ~* (sw\.js|manifest\.webmanifest|manifest\.json)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        access_log off;
    }

    # Cache control for index.html
    location = /index.html {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    # Set cache control for all other static assets
    location ~* \.(?:css|js|jpg|svg|png|gif|ico|eot|woff|woff2|ttf|json)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
