replicaCount: 1

image:
  repository: ghcr.io/johnfawzy84/FinInsightAI
  pullPolicy: IfNotPresent
  # tag: "latest"
  tag: "{{ .Chart.AppVersion }}"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

