apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finsightai.fullname" . }}
  labels:
    {{- include "finsightai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "finsightai.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "finsightai.fullname" . }}
        {{- include "finsightai.labels" . | nindent 8 }}
    spec:
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
      containers:
        - name: finsightai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
    {{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
    {{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
